[package]
name = "raphael-bindings"
version = "0.1.0"
edition = "2024"

[lib]
name = "raphael_bindings"
crate-type = ["cdylib"]

[dependencies]
raphael-sim = { path = "../raphael-rs/raphael-sim" }
raphael-solver = { path = "../raphael-rs/raphael-solver" }
rayon = "1.11"
log = { version = "0.4", features = ["std"] }

[build-dependencies]
cbindgen = "0.29.2"
csbindgen = "1.9.3"
