[package]
name = "raphael-bindings"
version = "0.1.0"
edition = "2024"

[lib]
name = "raphael_bindings"
crate-type = ["cdylib"]

[dependencies]
raphael-sim = { git = "https://github.com/KonaeAkira/raphael-rs.git", branch = "preview" }
raphael-solver = { git = "https://github.com/KonaeAkira/raphael-rs.git", branch = "preview" }
rayon = "*"
log = { version = "*", features = ["std"] }

[build-dependencies]
cbindgen = "0.29.2"
csbindgen = "1.9.3"
